In [2]:
import os
import numpy as np
import cv2
from tensorflow.keras.applications import VGG16
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten
from tensorflow.keras.optimizers import Adam
from sklearn.model_selection import train_test_split
from tensorflow.keras.applications.vgg16 import VGG16, preprocess_input

In [33]:
img_width, img_height = 224, 224
num_classes = 2
epochs = 5
batch_size = 32

# Load images and labels
images = []
labels = []

In [34]:
image_dir = "C:\\Users\91992\Desktop\Deep Learning Project\Images 2"
for filename in os.listdir(image_dir):
    if filename.endswith(".jpeg"):
        image = cv2.imread(os.path.join(image_dir, filename))
        image = cv2.resize(image, (img_width, img_height))
        images.append(image)
        
        # Assuming all images are labeled as 1 (rip tide) for now
        labels.append(1) 

In [35]:
images

[array([[[226, 214, 208],
         [226, 214, 208],
         [226, 214, 208],
         ...,
         [223, 205, 198],
         [223, 205, 198],
         [223, 205, 198]],
 
        [[225, 213, 207],
         [225, 213, 207],
         [226, 214, 208],
         ...,
         [222, 204, 197],
         [222, 204, 197],
         [222, 204, 197]],
 
        [[224, 212, 206],
         [224, 212, 206],
         [225, 213, 207],
         ...,
         [220, 203, 196],
         [220, 203, 196],
         [220, 203, 196]],
 
        ...,
 
        [[145, 154, 158],
         [145, 154, 158],
         [145, 154, 158],
         ...,
         [145, 152, 157],
         [145, 152, 156],
         [145, 152, 156]],
 
        [[146, 155, 159],
         [146, 155, 159],
         [145, 154, 158],
         ...,
         [146, 154, 158],
         [145, 154, 158],
         [145, 154, 158]],
 
        [[146, 155, 159],
         [146, 155, 159],
         [145, 154, 158],
         ...,
         [146, 154, 158],
  

In [36]:
image_dir_0 = "C:\\Users\91992\Desktop\Deep Learning Project\Images_tides2"

for filename in os.listdir(image_dir):
    if filename.endswith(".jpeg"):
        image = cv2.imread(os.path.join(image_dir, filename))
        image = cv2.resize(image, (img_width, img_height))
        images.append(image)
        
        # Assuming all images are labeled as 1 (rip tide) for now
        labels.append(0) 

In [37]:
images = np.array(images)
labels = np.array(labels)


In [38]:
X_train, X_test, y_train, y_test = train_test_split(images, labels, test_size=0.1, random_state=1)

In [39]:
X_train = preprocess_input(X_train)
X_test = preprocess_input(X_test)

In [40]:
base_model = VGG16(weights='imagenet', include_top=False, input_shape=(img_width, img_height, 3))

In [41]:
for layer in base_model.layers:
    layer.trainable = False


In [42]:
model = Sequential([
    base_model,
    Flatten(),
    Dense(256, activation='relu'),
    Dense(num_classes, activation='softmax')
])

In [43]:
model.compile(optimizer=Adam(), loss='sparse_categorical_crossentropy', metrics=['accuracy'])

In [44]:
model.fit(X_train, y_train, epochs=epochs, batch_size=batch_size, validation_data=(X_test, y_test))

Epoch 1/5
22/22 ━━━━━━━━━━━━━━━━━━━━ 53s 2s/step - accuracy: 0.4604 - loss: 27.6298 - val_accuracy: 0.3636 - val_loss: 5.9898
Epoch 2/5
22/22 ━━━━━━━━━━━━━━━━━━━━ 52s 2s/step - accuracy: 0.4834 - loss: 3.0768 - val_accuracy: 0.5195 - val_loss: 1.6253
Epoch 3/5
22/22 ━━━━━━━━━━━━━━━━━━━━ 58s 3s/step - accuracy: 0.4676 - loss: 0.7729 - val_accuracy: 0.5325 - val_loss: 1.5779
Epoch 4/5
22/22 ━━━━━━━━━━━━━━━━━━━━ 63s 3s/step - accuracy: 0.5241 - loss: 0.6973 - val_accuracy: 0.4286 - val_loss: 1.7156
Epoch 5/5
22/22 ━━━━━━━━━━━━━━━━━━━━ 63s 3s/step - accuracy: 0.4969 - loss: 0.7006 - val_accuracy: 0.7013 - val_loss: 1.6572


In [66]:
new_image_path = r"C:\\Users\91992\Desktop\Deep Learning Project\Images 2\1Gtuw&s.jpeg"

# Read and preprocess the new image
try:
    new_image = cv2.imread(new_image_path)
    new_image = cv2.resize(new_image, (img_width, img_height))
    new_image = np.expand_dims(new_image, axis=0)  # Add batch dimension
    new_image = VGG16.preprocess_input(new_image)
except Exception as e:
    print(e)

# Make predictions using the trained model
predictions = model.predict(new_image)

# Get the predicted class (1 for rip tide, 0 for non-rip tide)
predicted_class = np.argmax(predictions)

if predicted_class == 1:
    print("The model predicts that the image contains a rip tide.")
else:
    print("The model predicts that the image does not contain a rip tide.")

'function' object has no attribute 'preprocess_input'
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 218ms/step
The model predicts that the image does not contain a rip tide.


In [64]:
print(cv2.imread(r"C:\\Users\91992\Desktop\Deep Learning Project\Images 2\1Gtuw&s.jpeg"))

[[[118  99  61]
  [118  99  61]
  [117  98  60]
  ...
  [105  71  28]
  [105  71  28]
  [108  74  31]]

 [[ 98  79  41]
  [ 97  78  40]
  [ 97  78  40]
  ...
  [110  78  37]
  [110  78  37]
  [ 99  67  26]]

 [[101  82  44]
  [101  82  44]
  [100  81  43]
  ...
  [101  73  38]
  [101  73  38]
  [ 96  68  33]]

 ...

 [[141 175 199]
  [141 175 199]
  [141 175 199]
  ...
  [120 163 196]
  [118 163 196]
  [115 160 193]]

 [[137 173 197]
  [137 173 197]
  [137 173 197]
  ...
  [123 164 196]
  [121 165 196]
  [121 165 196]]

 [[137 173 197]
  [137 173 197]
  [137 173 197]
  ...
  [123 165 194]
  [123 165 194]
  [121 165 194]]]


In [ ]:
ample_image = X_test[0]
sample_image = np.expand_dims(sample_image, axis=0)
predictions = model.predict(sample_image)
print("Predictions:", predictions)

# Visualize the predictions on the sample image
detections = {"detection_boxes": predictions['detection_boxes'][0],
              "detection_classes": predictions['detection_classes'][0],
              "detection_scores": predictions['detection_scores'][0]}

image_np_with_detections = sample_image.copy()
viz_utils.visualize_boxes_and_labels_on_image_array(
    image_np_with_detections[0],
    detections['detection_boxes'],
    detections['detection_classes'],
    detections['detection_scores'],
    category_index,
    use_normalized_coordinates=True,
    max_boxes_to_draw=200,
    min_score_thresh=.30,
    agnostic_mode=False)

# Display the image with bounding boxes
from matplotlib import pyplot as plt
plt.figure(figsize=(12, 16))
plt.imshow(image_np_with_detections[0])
plt.show()